[package]
name = "scrape"
version = "0.1.0"
authors = ["Nils Wireklint <nils@wireklint.se>"]

[dependencies]
url = "1.4.0"
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.6"
curl = "0.4.2"
clap = "2.2.0"
time = "0.1.0"
csv = "1.0.0-beta.3"
